// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ksolexp.Model;

#nullable disable

namespace solexp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("solexp.Model.Account_transaction", b =>
                {
                    b.Property<int>("id_transaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_transaction"));

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int>("id_client")
                        .HasColumnType("integer");

                    b.Property<int?>("id_lesson_student")
                        .HasColumnType("integer");

                    b.Property<string>("payment_method")
                        .HasColumnType("text");

                    b.Property<DateTime?>("transaction_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("type")
                        .HasColumnType("text");

                    b.HasKey("id_transaction");

                    b.ToTable("AccountTransactions");
                });

            modelBuilder.Entity("solexp.Model.Admin", b =>
                {
                    b.Property<int>("id_admin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_admin"));

                    b.Property<string>("full_name")
                        .HasColumnType("text");

                    b.Property<int>("id_user")
                        .HasColumnType("integer");

                    b.Property<string>("phone_number")
                        .HasColumnType("text");

                    b.HasKey("id_admin");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("solexp.Model.Client", b =>
                {
                    b.Property<int>("id_client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_client"));

                    b.Property<decimal>("balance")
                        .HasColumnType("numeric");

                    b.Property<string>("full_name")
                        .HasColumnType("text");

                    b.Property<int>("id_user")
                        .HasColumnType("integer");

                    b.Property<string>("phone_number")
                        .HasColumnType("text");

                    b.HasKey("id_client");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("solexp.Model.Cours", b =>
                {
                    b.Property<int>("id_cours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_cours"));

                    b.Property<int?>("count_lesson")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<decimal?>("price_per_class")
                        .HasColumnType("numeric");

                    b.HasKey("id_cours");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("solexp.Model.Lesson", b =>
                {
                    b.Property<int>("id_lesson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_lesson"));

                    b.Property<string>("classroom")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int?>("duration_min")
                        .HasColumnType("integer");

                    b.Property<string>("homework")
                        .HasColumnType("text");

                    b.Property<int>("id_course")
                        .HasColumnType("integer");

                    b.Property<int>("id_teacher")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("lesson_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("number_in_course")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.HasKey("id_lesson");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("solexp.Model.Lesson_student", b =>
                {
                    b.Property<int>("id_lesson_student")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_lesson_student"));

                    b.Property<string>("attendance_status")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("feedback")
                        .HasColumnType("text");

                    b.Property<int?>("homework_percent")
                        .HasColumnType("integer");

                    b.Property<int>("id_lesson")
                        .HasColumnType("integer");

                    b.Property<int>("id_student")
                        .HasColumnType("integer");

                    b.Property<int?>("score")
                        .HasColumnType("integer");

                    b.HasKey("id_lesson_student");

                    b.ToTable("LessonStudents");
                });

            modelBuilder.Entity("solexp.Model.Role", b =>
                {
                    b.Property<int>("id_role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_role"));

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("role_name")
                        .HasColumnType("text");

                    b.HasKey("id_role");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("solexp.Model.Student", b =>
                {
                    b.Property<int>("id_student")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_student"));

                    b.Property<DateTime?>("birth_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("full_name")
                        .HasColumnType("text");

                    b.Property<int>("id_client")
                        .HasColumnType("integer");

                    b.HasKey("id_student");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("solexp.Model.Teacher", b =>
                {
                    b.Property<int>("id_teacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_teacher"));

                    b.Property<string>("full_name")
                        .HasColumnType("text");

                    b.Property<int>("id_user")
                        .HasColumnType("integer");

                    b.Property<string>("phone_number")
                        .HasColumnType("text");

                    b.Property<string>("specialization")
                        .HasColumnType("text");

                    b.HasKey("id_teacher");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("solexp.Model.User", b =>
                {
                    b.Property<int>("id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_user"));

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<int>("id_role")
                        .HasColumnType("integer");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.HasKey("id_user");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
